#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Wed Sep 12 09:38:53 2018
#

import wx
import random
import wx.lib.inspection
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        wx.lib.inspection.InspectionTool().Show()
        # begin wxGlade: MyWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE | wx.FULL_REPAINT_ON_RESIZE | wx.MAXIMIZE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((600, 250))
        self.combo_box_algoritmo = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.button_import = wx.Button(self, wx.ID_ANY, "Selecionar")
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.selecionar, self.button_import)
        # end wxGlade
        self.barras = []
        self.size = 5
        

    def __set_properties(self):
        # begin wxGlade: MyWindow.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyWindow.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        label_algoritmo = wx.StaticText(self, wx.ID_ANY, "Algoritmo:")
        sizer_3.Add(label_algoritmo, 0, wx.ALIGN_CENTER, 0)
        sizer_3.Add(self.combo_box_algoritmo, 0, wx.ALIGN_CENTER, 0)
        sizer_3.Add(self.button_import, 0, wx.ALIGN_CENTER, 0)
        self.sizer_main.Add(sizer_3, 0, wx.EXPAND, 0)
        self.sizer_main.Add(self.text_ctrl_1, 0, 0, 0)
        self.sizer_main.Add((0, 0), 0, 0, 0)
        sizer_1.Add(self.sizer_main, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade
        self.sizer_barras = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_main.Add(self.sizer_barras, 1, wx.EXPAND, 0)

    def selecionar(self, event):  # wxGlade: MyWindow.<event_handler>
        for x in self.sizer_barras.GetChildren():
            print(x.DeleteWindows())
        self.barras =[]
        self.sizer_barras.Clear()

        self.criarSizerBarras()
        self.Layout()


    def criarSizerBarras(self):
        for x in range(0, self.size):
            self.barras.append(self.criarBarra())
            self.sizer_barras.Add(self.barras[x], 0, wx.EXPAND, 0)
        order = (list(range(0, self.size))[:])
        random.shuffle(order)
        i = 0
        for x in order:
            self.barras[x].SetValue(i)
            i+=1

    def pegarLargura(self):
        print((self.GetSize()[0])/(self.size))
        return (self.GetSize()[0])/(self.size)

    def criarBarra(self):
        gauge = wx.Gauge(self, wx.ID_ANY, self.size-1,
                        style= wx.GA_VERTICAL)
        gauge.SetMinSize((self.pegarLargura(), 283))
        gauge.SetValue(0)
        return gauge

# end of class MyWindow

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyWindow(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
